site_name: ZIMO Docs
site_description: Produktdokumentasjon og nedlastinger (STEP, PDF, datablad, firmware)
site_url: https://docs.zimo.no/

theme:
  name: material
  logo: assets/logos/ZimoLogoWhite.svg
  language: en

  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Lys modus
    - scheme: default
      toggle:
        icon: material/weather-night
        name: MÃ¸rk modus

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search

repo_name: ZIMO-AS/zimo-docs
repo_url: https://github.com/zimo-subsea/


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  homepage: https://zimo.no

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js

nav:
  - Home: https://zimo.no
  - Products:
      - Camera System: products/camera-system/index.md
      - Lights: products/lights/index.md
      - FOG Gyro: products/fog-gyro/index.md
      - Quartz Pressure Sensor: products/quartz-pressure-sensor/index.md
      - Subsea Converter: products/subsea-converter/index.md
      - Subsea Display: products/subsea-display/index.md
